version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  azure-vote-back:
      image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
      container_name: azure-vote-back
      environment:
        ALLOW_EMPTY_PASSWORD: "yes"
      ports:
        - "6379:6379"